// Generated by rstantools.  Do not edit by hand.

/*
    priordata is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    priordata is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with priordata.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_mean_mcmc_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 27> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 18, column 2 to column 13)",
  " (in 'string', line 19, column 2 to column 21)",
  " (in 'string', line 24, column 2 to column 53)",
  " (in 'string', line 25, column 2 to column 17)",
  " (in 'string', line 27, column 4 to column 77)",
  " (in 'string', line 26, column 19 to line 28, column 3)",
  " (in 'string', line 26, column 2 to line 28, column 3)",
  " (in 'string', line 29, column 2 to column 34)",
  " (in 'string', line 30, column 2 to column 26)",
  " (in 'string', line 34, column 4 to column 29)",
  " (in 'string', line 35, column 4 to column 29)",
  " (in 'string', line 33, column 9 to line 36, column 3)",
  " (in 'string', line 32, column 4 to column 29)",
  " (in 'string', line 31, column 14 to line 33, column 3)",
  " (in 'string', line 31, column 2 to line 36, column 3)",
  " (in 'string', line 7, column 2 to column 20)",
  " (in 'string', line 8, column 9 to column 13)",
  " (in 'string', line 8, column 2 to column 21)",
  " (in 'string', line 9, column 9 to column 13)",
  " (in 'string', line 9, column 2 to column 19)",
  " (in 'string', line 10, column 9 to column 13)",
  " (in 'string', line 10, column 2 to column 21)",
  " (in 'string', line 13, column 2 to column 12)",
  " (in 'string', line 14, column 2 to column 19)",
  " (in 'string', line 15, column 2 to column 28)",
  " (in 'string', line 19, column 9 to column 13)"};
#include <stan_meta_header.hpp>
class model_mean_mcmc final : public model_base_crtp<model_mean_mcmc> {
private:
  int nmix;
  Eigen::Matrix<double,-1,1> means_data__;
  Eigen::Matrix<double,-1,1> sds_data__;
  Eigen::Matrix<double,-1,1> probs_data__;
  double ybar;
  double se;
  int pred;
  Eigen::Map<Eigen::Matrix<double,-1,1>> means{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sds{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> probs{nullptr, 0};
public:
  ~model_mean_mcmc() {}
  model_mean_mcmc(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_mean_mcmc_namespace::model_mean_mcmc";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "nmix", "int",
        std::vector<size_t>{});
      nmix = std::numeric_limits<int>::min();
      current_statement__ = 16;
      nmix = context__.vals_i("nmix")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "nmix", nmix, 1);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("means", "nmix", nmix);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "means", "double",
        std::vector<size_t>{static_cast<size_t>(nmix)});
      means_data__ = Eigen::Matrix<double,-1,1>::Constant(nmix,
                       std::numeric_limits<double>::quiet_NaN());
      new (&means)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(means_data__.data(), nmix);
      {
        std::vector<local_scalar_t__> means_flat__;
        current_statement__ = 18;
        means_flat__ = context__.vals_r("means");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= nmix; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(means, means_flat__[(pos__ - 1)],
            "assigning variable means", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("sds", "nmix", nmix);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "sds", "double",
        std::vector<size_t>{static_cast<size_t>(nmix)});
      sds_data__ = Eigen::Matrix<double,-1,1>::Constant(nmix,
                     std::numeric_limits<double>::quiet_NaN());
      new (&sds) Eigen::Map<Eigen::Matrix<double,-1,1>>(sds_data__.data(),
        nmix);
      {
        std::vector<local_scalar_t__> sds_flat__;
        current_statement__ = 20;
        sds_flat__ = context__.vals_r("sds");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= nmix; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(sds, sds_flat__[(pos__ - 1)],
            "assigning variable sds", stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("probs", "nmix", nmix);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "probs", "double",
        std::vector<size_t>{static_cast<size_t>(nmix)});
      probs_data__ = Eigen::Matrix<double,-1,1>::Constant(nmix,
                       std::numeric_limits<double>::quiet_NaN());
      new (&probs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(probs_data__.data(), nmix);
      {
        std::vector<local_scalar_t__> probs_flat__;
        current_statement__ = 22;
        probs_flat__ = context__.vals_r("probs");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= nmix; ++sym1__) {
          current_statement__ = 22;
          stan::model::assign(probs, probs_flat__[(pos__ - 1)],
            "assigning variable probs", stan::model::index_uni(sym1__));
          current_statement__ = 22;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      context__.validate_dims("data initialization", "ybar", "double",
        std::vector<size_t>{});
      ybar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 23;
      ybar = context__.vals_r("ybar")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization", "se", "double",
        std::vector<size_t>{});
      se = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 24;
      se = context__.vals_r("se")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "se", se, 0);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "pred", "int",
        std::vector<size_t>{});
      pred = std::numeric_limits<int>::min();
      current_statement__ = 25;
      pred = context__.vals_i("pred")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "pred", pred, 0);
      current_statement__ = 25;
      stan::math::check_less_or_equal(function__, "pred", pred, 1);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("alpha", "pred", pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + pred;
  }
  inline std::string model_name() const final {
    return "model_mean_mcmc";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_mean_mcmc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ ymean = DUMMY_VAR__;
      current_statement__ = 1;
      ymean = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(pred, DUMMY_VAR__);
      current_statement__ = 2;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(pred);
      {
        local_scalar_t__ prior_dens = DUMMY_VAR__;
        local_scalar_t__ prior_logdens = DUMMY_VAR__;
        local_scalar_t__ prior_logdens_surv = DUMMY_VAR__;
        current_statement__ = 4;
        prior_dens = 0;
        current_statement__ = 7;
        for (int i = 1; i <= nmix; ++i) {
          current_statement__ = 5;
          prior_dens = (prior_dens +
            stan::math::exp(
              (stan::math::log(
                 stan::model::rvalue(probs, "probs",
                   stan::model::index_uni(i))) +
              stan::math::normal_lpdf<false>(ymean,
                stan::model::rvalue(means, "means", stan::model::index_uni(i)),
                stan::model::rvalue(sds, "sds", stan::model::index_uni(i))))));
        }
        current_statement__ = 8;
        prior_logdens = stan::math::log(prior_dens);
        current_statement__ = 9;
        lp_accum__.add(prior_logdens);
        current_statement__ = 15;
        if (stan::math::logical_eq(pred, 0)) {
          current_statement__ = 13;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(ybar, ymean, se));
        } else {
          current_statement__ = 10;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, ymean, 1));
          current_statement__ = 11;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(ybar, alpha, se));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_mean_mcmc_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double ymean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      ymean = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> alpha =
        Eigen::Matrix<double,-1,1>::Constant(pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      alpha = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(pred);
      out__.write(ymean);
      out__.write(alpha);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ ymean = DUMMY_VAR__;
      current_statement__ = 1;
      ymean = in__.read<local_scalar_t__>();
      out__.write(ymean);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(pred, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(pred),
        "assigning variable alpha");
      out__.write(alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "ymean", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(pred)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ ymean = DUMMY_VAR__;
      current_statement__ = 1;
      ymean = context__.vals_r("ymean")[(1 - 1)];
      out__.write(ymean);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 2;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= pred; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"ymean", "alpha"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(pred)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "ymean");
    for (int sym1__ = 1; sym1__ <= pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "ymean");
    for (int sym1__ = 1; sym1__ <= pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"ymean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(pred) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"ymean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(pred) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + pred);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + pred);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_mean_mcmc_namespace::model_mean_mcmc;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_mean_mcmc_namespace::profiles__;
}
#endif
#endif
