// Generated by rstantools.  Do not edit by hand.

/*
    priordata is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    priordata is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with priordata.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_height_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 80> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 25, column 2 to column 14)",
  " (in 'string', line 26, column 2 to column 14)",
  " (in 'string', line 27, column 2 to column 14)",
  " (in 'string', line 28, column 2 to column 28)",
  " (in 'string', line 29, column 2 to column 34)",
  " (in 'string', line 30, column 2 to column 21)",
  " (in 'string', line 31, column 2 to column 23)",
  " (in 'string', line 34, column 2 to column 34)",
  " (in 'string', line 35, column 2 to column 34)",
  " (in 'string', line 36, column 2 to column 19)",
  " (in 'string', line 37, column 2 to column 34)",
  " (in 'string', line 38, column 2 to column 20)",
  " (in 'string', line 39, column 2 to column 58)",
  " (in 'string', line 40, column 2 to column 48)",
  " (in 'string', line 66, column 2 to column 29)",
  " (in 'string', line 67, column 2 to column 27)",
  " (in 'string', line 69, column 4 to column 53)",
  " (in 'string', line 71, column 6 to column 59)",
  " (in 'string', line 70, column 23 to line 72, column 5)",
  " (in 'string', line 70, column 4 to line 72, column 5)",
  " (in 'string', line 68, column 17 to line 73, column 3)",
  " (in 'string', line 68, column 2 to line 73, column 3)",
  " (in 'string', line 43, column 9 to column 10)",
  " (in 'string', line 43, column 2 to column 24)",
  " (in 'string', line 44, column 9 to column 15)",
  " (in 'string', line 44, column 2 to column 27)",
  " (in 'string', line 45, column 2 to column 24)",
  " (in 'string', line 46, column 2 to column 25)",
  " (in 'string', line 47, column 2 to column 24)",
  " (in 'string', line 48, column 2 to column 24)",
  " (in 'string', line 49, column 2 to column 28)",
  " (in 'string', line 50, column 2 to column 31)",
  " (in 'string', line 52, column 4 to column 50)",
  " (in 'string', line 53, column 4 to column 44)",
  " (in 'string', line 51, column 12 to line 54, column 3)",
  " (in 'string', line 51, column 2 to line 54, column 3)",
  " (in 'string', line 56, column 4 to column 53)",
  " (in 'string', line 60, column 6 to column 43)",
  " (in 'string', line 61, column 6 to column 41)",
  " (in 'string', line 59, column 23 to line 62, column 5)",
  " (in 'string', line 59, column 11 to line 62, column 5)",
  " (in 'string', line 58, column 6 to column 45)",
  " (in 'string', line 57, column 16 to line 59, column 5)",
  " (in 'string', line 57, column 4 to line 62, column 5)",
  " (in 'string', line 55, column 17 to line 63, column 3)",
  " (in 'string', line 55, column 2 to line 63, column 3)",
  " (in 'string', line 8, column 2 to column 17)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 2 to column 19)",
  " (in 'string', line 10, column 9 to column 10)",
  " (in 'string', line 10, column 2 to column 16)",
  " (in 'string', line 11, column 2 to column 22)",
  " (in 'string', line 12, column 9 to column 15)",
  " (in 'string', line 12, column 2 to column 26)",
  " (in 'string', line 13, column 9 to column 15)",
  " (in 'string', line 13, column 2 to column 27)",
  " (in 'string', line 14, column 9 to column 15)",
  " (in 'string', line 14, column 2 to column 25)",
  " (in 'string', line 15, column 2 to column 28)",
  " (in 'string', line 16, column 2 to column 22)",
  " (in 'string', line 17, column 9 to column 15)",
  " (in 'string', line 17, column 2 to column 26)",
  " (in 'string', line 18, column 2 to column 11)",
  " (in 'string', line 18, column 12 to column 21)",
  " (in 'string', line 18, column 22 to column 31)",
  " (in 'string', line 18, column 32 to column 41)",
  " (in 'string', line 19, column 2 to column 11)",
  " (in 'string', line 19, column 12 to column 21)",
  " (in 'string', line 20, column 2 to column 12)",
  " (in 'string', line 20, column 13 to column 23)",
  " (in 'string', line 21, column 2 to column 16)",
  " (in 'string', line 21, column 17 to column 31)",
  " (in 'string', line 22, column 2 to column 11)",
  " (in 'string', line 22, column 12 to column 21)",
  " (in 'string', line 31, column 9 to column 15)",
  " (in 'string', line 66, column 9 to column 15)",
  " (in 'string', line 67, column 9 to column 15)",
  " (in 'string', line 4, column 4 to column 82)",
  " (in 'string', line 3, column 72 to line 5, column 3)"};
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__,
                T4__, stan::promote_args_t<T5__>>,-1,1>
PB1(const T0__& age_arg__, const T1__& h0, const T2__& h1, const T3__& s0,
    const T4__& s1, const T5__& gamma, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T2__, T3__,
                T4__, stan::promote_args_t<T5__>>,-1,1>
PB1(const T0__& age_arg__, const T1__& h0, const T2__& h1, const T3__& s0,
    const T4__& s1, const T5__& gamma, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, T2__, T3__, T4__,
                             stan::promote_args_t<T5__>>;
  int current_statement__ = 0;
  const auto& age = stan::math::to_ref(age_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 78;
    return stan::math::subtract(h1,
             stan::math::elt_divide((2. * (h1 - h0)),
               stan::math::add(
                 stan::math::exp(
                   stan::math::elt_multiply(s0,
                     stan::math::subtract(age, gamma))),
                 stan::math::exp(
                   stan::math::elt_multiply(s1,
                     stan::math::subtract(age, gamma))))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_height final : public model_base_crtp<model_height> {
private:
  int n;
  Eigen::Matrix<double,-1,1> height_data__;
  Eigen::Matrix<double,-1,1> age_data__;
  int n_elic;
  Eigen::Matrix<double,-1,1> age_elic_data__;
  Eigen::Matrix<double,-1,1> ybar_elic_data__;
  Eigen::Matrix<double,-1,1> se_elic_data__;
  int pred;
  int n_pred;
  Eigen::Matrix<double,-1,1> age_pred_data__;
  double ms0;
  double ss0;
  double mds;
  double sds;
  double mh1;
  double sh1;
  double ph0a;
  double ph0b;
  double mingamma;
  double maxgamma;
  double msd;
  double ssd;
  Eigen::Map<Eigen::Matrix<double,-1,1>> height{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> age{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> age_elic{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> ybar_elic{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> se_elic{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> age_pred{nullptr, 0};
public:
  ~model_height() {}
  model_height(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_height_namespace::model_height";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 47;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 47;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("height", "n", n);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "height", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      height_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                        std::numeric_limits<double>::quiet_NaN());
      new (&height)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(height_data__.data(), n);
      {
        std::vector<local_scalar_t__> height_flat__;
        current_statement__ = 49;
        height_flat__ = context__.vals_r("height");
        current_statement__ = 49;
        pos__ = 1;
        current_statement__ = 49;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 49;
          stan::model::assign(height, height_flat__[(pos__ - 1)],
            "assigning variable height", stan::model::index_uni(sym1__));
          current_statement__ = 49;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 50;
      stan::math::validate_non_negative_index("age", "n", n);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "age", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      age_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                     std::numeric_limits<double>::quiet_NaN());
      new (&age) Eigen::Map<Eigen::Matrix<double,-1,1>>(age_data__.data(), n);
      {
        std::vector<local_scalar_t__> age_flat__;
        current_statement__ = 51;
        age_flat__ = context__.vals_r("age");
        current_statement__ = 51;
        pos__ = 1;
        current_statement__ = 51;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 51;
          stan::model::assign(age, age_flat__[(pos__ - 1)],
            "assigning variable age", stan::model::index_uni(sym1__));
          current_statement__ = 51;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 52;
      context__.validate_dims("data initialization", "n_elic", "int",
        std::vector<size_t>{});
      n_elic = std::numeric_limits<int>::min();
      current_statement__ = 52;
      n_elic = context__.vals_i("n_elic")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "n_elic", n_elic, 0);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("age_elic", "n_elic", n_elic);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "age_elic", "double",
        std::vector<size_t>{static_cast<size_t>(n_elic)});
      age_elic_data__ = Eigen::Matrix<double,-1,1>::Constant(n_elic,
                          std::numeric_limits<double>::quiet_NaN());
      new (&age_elic)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(age_elic_data__.data(),
        n_elic);
      {
        std::vector<local_scalar_t__> age_elic_flat__;
        current_statement__ = 54;
        age_elic_flat__ = context__.vals_r("age_elic");
        current_statement__ = 54;
        pos__ = 1;
        current_statement__ = 54;
        for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
          current_statement__ = 54;
          stan::model::assign(age_elic, age_elic_flat__[(pos__ - 1)],
            "assigning variable age_elic", stan::model::index_uni(sym1__));
          current_statement__ = 54;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("ybar_elic", "n_elic", n_elic);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "ybar_elic", "double",
        std::vector<size_t>{static_cast<size_t>(n_elic)});
      ybar_elic_data__ = Eigen::Matrix<double,-1,1>::Constant(n_elic,
                           std::numeric_limits<double>::quiet_NaN());
      new (&ybar_elic)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(ybar_elic_data__.data(),
        n_elic);
      {
        std::vector<local_scalar_t__> ybar_elic_flat__;
        current_statement__ = 56;
        ybar_elic_flat__ = context__.vals_r("ybar_elic");
        current_statement__ = 56;
        pos__ = 1;
        current_statement__ = 56;
        for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
          current_statement__ = 56;
          stan::model::assign(ybar_elic, ybar_elic_flat__[(pos__ - 1)],
            "assigning variable ybar_elic", stan::model::index_uni(sym1__));
          current_statement__ = 56;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      stan::math::validate_non_negative_index("se_elic", "n_elic", n_elic);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "se_elic", "double",
        std::vector<size_t>{static_cast<size_t>(n_elic)});
      se_elic_data__ = Eigen::Matrix<double,-1,1>::Constant(n_elic,
                         std::numeric_limits<double>::quiet_NaN());
      new (&se_elic)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(se_elic_data__.data(), n_elic);
      {
        std::vector<local_scalar_t__> se_elic_flat__;
        current_statement__ = 58;
        se_elic_flat__ = context__.vals_r("se_elic");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
          current_statement__ = 58;
          stan::model::assign(se_elic, se_elic_flat__[(pos__ - 1)],
            "assigning variable se_elic", stan::model::index_uni(sym1__));
          current_statement__ = 58;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 59;
      context__.validate_dims("data initialization", "pred", "int",
        std::vector<size_t>{});
      pred = std::numeric_limits<int>::min();
      current_statement__ = 59;
      pred = context__.vals_i("pred")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "pred", pred, 0);
      current_statement__ = 59;
      stan::math::check_less_or_equal(function__, "pred", pred, 1);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "n_pred", "int",
        std::vector<size_t>{});
      n_pred = std::numeric_limits<int>::min();
      current_statement__ = 60;
      n_pred = context__.vals_i("n_pred")[(1 - 1)];
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "n_pred", n_pred, 0);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("age_pred", "n_pred", n_pred);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "age_pred", "double",
        std::vector<size_t>{static_cast<size_t>(n_pred)});
      age_pred_data__ = Eigen::Matrix<double,-1,1>::Constant(n_pred,
                          std::numeric_limits<double>::quiet_NaN());
      new (&age_pred)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(age_pred_data__.data(),
        n_pred);
      {
        std::vector<local_scalar_t__> age_pred_flat__;
        current_statement__ = 62;
        age_pred_flat__ = context__.vals_r("age_pred");
        current_statement__ = 62;
        pos__ = 1;
        current_statement__ = 62;
        for (int sym1__ = 1; sym1__ <= n_pred; ++sym1__) {
          current_statement__ = 62;
          stan::model::assign(age_pred, age_pred_flat__[(pos__ - 1)],
            "assigning variable age_pred", stan::model::index_uni(sym1__));
          current_statement__ = 62;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 63;
      context__.validate_dims("data initialization", "ms0", "double",
        std::vector<size_t>{});
      ms0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 63;
      ms0 = context__.vals_r("ms0")[(1 - 1)];
      current_statement__ = 64;
      context__.validate_dims("data initialization", "ss0", "double",
        std::vector<size_t>{});
      ss0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 64;
      ss0 = context__.vals_r("ss0")[(1 - 1)];
      current_statement__ = 65;
      context__.validate_dims("data initialization", "mds", "double",
        std::vector<size_t>{});
      mds = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 65;
      mds = context__.vals_r("mds")[(1 - 1)];
      current_statement__ = 66;
      context__.validate_dims("data initialization", "sds", "double",
        std::vector<size_t>{});
      sds = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 66;
      sds = context__.vals_r("sds")[(1 - 1)];
      current_statement__ = 67;
      context__.validate_dims("data initialization", "mh1", "double",
        std::vector<size_t>{});
      mh1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 67;
      mh1 = context__.vals_r("mh1")[(1 - 1)];
      current_statement__ = 68;
      context__.validate_dims("data initialization", "sh1", "double",
        std::vector<size_t>{});
      sh1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 68;
      sh1 = context__.vals_r("sh1")[(1 - 1)];
      current_statement__ = 69;
      context__.validate_dims("data initialization", "ph0a", "double",
        std::vector<size_t>{});
      ph0a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 69;
      ph0a = context__.vals_r("ph0a")[(1 - 1)];
      current_statement__ = 70;
      context__.validate_dims("data initialization", "ph0b", "double",
        std::vector<size_t>{});
      ph0b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 70;
      ph0b = context__.vals_r("ph0b")[(1 - 1)];
      current_statement__ = 71;
      context__.validate_dims("data initialization", "mingamma", "double",
        std::vector<size_t>{});
      mingamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 71;
      mingamma = context__.vals_r("mingamma")[(1 - 1)];
      current_statement__ = 72;
      context__.validate_dims("data initialization", "maxgamma", "double",
        std::vector<size_t>{});
      maxgamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 72;
      maxgamma = context__.vals_r("maxgamma")[(1 - 1)];
      current_statement__ = 73;
      context__.validate_dims("data initialization", "msd", "double",
        std::vector<size_t>{});
      msd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 73;
      msd = context__.vals_r("msd")[(1 - 1)];
      current_statement__ = 74;
      context__.validate_dims("data initialization", "ssd", "double",
        std::vector<size_t>{});
      ssd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 74;
      ssd = context__.vals_r("ssd")[(1 - 1)];
      current_statement__ = 75;
      stan::math::validate_non_negative_index("alpha", "n_elic", n_elic);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("height_pred", "n_pred", n_pred);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("mean_pred", "n_pred", n_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + n_elic;
  }
  inline std::string model_name() const final {
    return "model_height";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_height_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ h1_std = DUMMY_VAR__;
      current_statement__ = 1;
      h1_std = in__.template read<local_scalar_t__>();
      local_scalar_t__ s0_std = DUMMY_VAR__;
      current_statement__ = 2;
      s0_std = in__.template read<local_scalar_t__>();
      local_scalar_t__ ds_std = DUMMY_VAR__;
      current_statement__ = 3;
      ds_std = in__.template read<local_scalar_t__>();
      local_scalar_t__ ph0 = DUMMY_VAR__;
      current_statement__ = 4;
      ph0 = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      local_scalar_t__ gamma_std = DUMMY_VAR__;
      current_statement__ = 5;
      gamma_std = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      local_scalar_t__ sd_height_std = DUMMY_VAR__;
      current_statement__ = 6;
      sd_height_std = in__.template read<local_scalar_t__>();
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_elic, DUMMY_VAR__);
      current_statement__ = 7;
      alpha = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(n_elic);
      local_scalar_t__ ds = DUMMY_VAR__;
      current_statement__ = 8;
      ds = stan::math::exp(((ds_std * sds) + mds));
      local_scalar_t__ h1 = DUMMY_VAR__;
      current_statement__ = 9;
      h1 = stan::math::exp(((h1_std * sh1) + mh1));
      local_scalar_t__ h0 = DUMMY_VAR__;
      current_statement__ = 10;
      h0 = (h1 * ph0);
      local_scalar_t__ s0 = DUMMY_VAR__;
      current_statement__ = 11;
      s0 = stan::math::exp(((s0_std * ss0) + ms0));
      local_scalar_t__ s1 = DUMMY_VAR__;
      current_statement__ = 12;
      s1 = (s0 + ds);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 13;
      gamma = (mingamma + (gamma_std * (maxgamma - mingamma)));
      local_scalar_t__ sd_height = DUMMY_VAR__;
      current_statement__ = 14;
      sd_height = stan::math::exp(((sd_height_std * ssd) + msd));
      {
        current_statement__ = 23;
        stan::math::validate_non_negative_index("mean_height", "n", n);
        Eigen::Matrix<local_scalar_t__,-1,1> mean_height =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("mean_elic", "n_elic", n_elic);
        Eigen::Matrix<local_scalar_t__,-1,1> mean_elic =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_elic, DUMMY_VAR__);
        current_statement__ = 27;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(h1_std));
        current_statement__ = 28;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(ph0, ph0a, ph0b));
        current_statement__ = 29;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(s0_std));
        current_statement__ = 30;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(ds_std));
        current_statement__ = 31;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(gamma_std, 0, 1));
        current_statement__ = 32;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(sd_height_std));
        current_statement__ = 36;
        if (stan::math::logical_gt(n, 0)) {
          current_statement__ = 33;
          stan::model::assign(mean_height,
            PB1(age, h0, h1, s0, s1, gamma, pstream__),
            "assigning variable mean_height");
          current_statement__ = 34;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(height,
                           mean_height, sd_height));
        }
        current_statement__ = 46;
        if (stan::math::logical_gt(n_elic, 0)) {
          current_statement__ = 37;
          stan::model::assign(mean_elic,
            PB1(age_elic, h0, h1, s0, s1, gamma, pstream__),
            "assigning variable mean_elic");
          current_statement__ = 44;
          if (stan::math::logical_eq(pred, 0)) {
            current_statement__ = 42;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(ybar_elic,
                             mean_elic, se_elic));
          } else {
            current_statement__ = 41;
            if (stan::math::logical_eq(pred, 1)) {
              current_statement__ = 38;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha,
                               mean_elic, sd_height));
              current_statement__ = 39;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(ybar_elic,
                               alpha, se_elic));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_height_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double h1_std = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      h1_std = in__.template read<local_scalar_t__>();
      double s0_std = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      s0_std = in__.template read<local_scalar_t__>();
      double ds_std = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      ds_std = in__.template read<local_scalar_t__>();
      double ph0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      ph0 = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      double gamma_std = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      gamma_std = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      double sd_height_std = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sd_height_std = in__.template read<local_scalar_t__>();
      Eigen::Matrix<double,-1,1> alpha =
        Eigen::Matrix<double,-1,1>::Constant(n_elic,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      alpha = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(n_elic);
      double ds = std::numeric_limits<double>::quiet_NaN();
      double h1 = std::numeric_limits<double>::quiet_NaN();
      double h0 = std::numeric_limits<double>::quiet_NaN();
      double s0 = std::numeric_limits<double>::quiet_NaN();
      double s1 = std::numeric_limits<double>::quiet_NaN();
      double gamma = std::numeric_limits<double>::quiet_NaN();
      double sd_height = std::numeric_limits<double>::quiet_NaN();
      out__.write(h1_std);
      out__.write(s0_std);
      out__.write(ds_std);
      out__.write(ph0);
      out__.write(gamma_std);
      out__.write(sd_height_std);
      out__.write(alpha);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 8;
      ds = stan::math::exp(((ds_std * sds) + mds));
      current_statement__ = 9;
      h1 = stan::math::exp(((h1_std * sh1) + mh1));
      current_statement__ = 10;
      h0 = (h1 * ph0);
      current_statement__ = 11;
      s0 = stan::math::exp(((s0_std * ss0) + ms0));
      current_statement__ = 12;
      s1 = (s0 + ds);
      current_statement__ = 13;
      gamma = (mingamma + (gamma_std * (maxgamma - mingamma)));
      current_statement__ = 14;
      sd_height = stan::math::exp(((sd_height_std * ssd) + msd));
      if (emit_transformed_parameters__) {
        out__.write(ds);
        out__.write(h1);
        out__.write(h0);
        out__.write(s0);
        out__.write(s1);
        out__.write(gamma);
        out__.write(sd_height);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> height_pred =
        Eigen::Matrix<double,-1,1>::Constant(n_pred,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> mean_pred =
        Eigen::Matrix<double,-1,1>::Constant(n_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 22;
      if (stan::math::logical_gt(n_pred, 0)) {
        current_statement__ = 17;
        stan::model::assign(mean_pred,
          PB1(age_pred, h0, h1, s0, s1, gamma, pstream__),
          "assigning variable mean_pred");
        current_statement__ = 20;
        for (int i = 1; i <= n_pred; ++i) {
          current_statement__ = 18;
          stan::model::assign(height_pred,
            stan::math::normal_rng(
              stan::model::rvalue(mean_pred, "mean_pred",
                stan::model::index_uni(i)), sd_height, base_rng__),
            "assigning variable height_pred", stan::model::index_uni(i));
        }
      }
      out__.write(height_pred);
      out__.write(mean_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ h1_std = DUMMY_VAR__;
      current_statement__ = 1;
      h1_std = in__.read<local_scalar_t__>();
      out__.write(h1_std);
      local_scalar_t__ s0_std = DUMMY_VAR__;
      current_statement__ = 2;
      s0_std = in__.read<local_scalar_t__>();
      out__.write(s0_std);
      local_scalar_t__ ds_std = DUMMY_VAR__;
      current_statement__ = 3;
      ds_std = in__.read<local_scalar_t__>();
      out__.write(ds_std);
      local_scalar_t__ ph0 = DUMMY_VAR__;
      current_statement__ = 4;
      ph0 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, ph0);
      local_scalar_t__ gamma_std = DUMMY_VAR__;
      current_statement__ = 5;
      gamma_std = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, gamma_std);
      local_scalar_t__ sd_height_std = DUMMY_VAR__;
      current_statement__ = 6;
      sd_height_std = in__.read<local_scalar_t__>();
      out__.write(sd_height_std);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_elic, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_elic),
        "assigning variable alpha");
      out__.write(alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "h1_std", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "s0_std", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "ds_std", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "ph0", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "gamma_std",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sd_height_std",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(n_elic)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ h1_std = DUMMY_VAR__;
      current_statement__ = 1;
      h1_std = context__.vals_r("h1_std")[(1 - 1)];
      out__.write(h1_std);
      local_scalar_t__ s0_std = DUMMY_VAR__;
      current_statement__ = 2;
      s0_std = context__.vals_r("s0_std")[(1 - 1)];
      out__.write(s0_std);
      local_scalar_t__ ds_std = DUMMY_VAR__;
      current_statement__ = 3;
      ds_std = context__.vals_r("ds_std")[(1 - 1)];
      out__.write(ds_std);
      local_scalar_t__ ph0 = DUMMY_VAR__;
      current_statement__ = 4;
      ph0 = context__.vals_r("ph0")[(1 - 1)];
      out__.write_free_lub(0, 1, ph0);
      local_scalar_t__ gamma_std = DUMMY_VAR__;
      current_statement__ = 5;
      gamma_std = context__.vals_r("gamma_std")[(1 - 1)];
      out__.write_free_lub(0, 1, gamma_std);
      local_scalar_t__ sd_height_std = DUMMY_VAR__;
      current_statement__ = 6;
      sd_height_std = context__.vals_r("sd_height_std")[(1 - 1)];
      out__.write(sd_height_std);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_elic, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 7;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(alpha);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"h1_std", "s0_std", "ds_std", "ph0",
                "gamma_std", "sd_height_std", "alpha"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"ds", "h1", "h0", "s0", "s1", "gamma", "sd_height"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"height_pred", "mean_pred"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(n_elic)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_pred)},
             std::vector<size_t>{static_cast<size_t>(n_pred)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "h1_std");
    param_names__.emplace_back(std::string() + "s0_std");
    param_names__.emplace_back(std::string() + "ds_std");
    param_names__.emplace_back(std::string() + "ph0");
    param_names__.emplace_back(std::string() + "gamma_std");
    param_names__.emplace_back(std::string() + "sd_height_std");
    for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "ds");
      param_names__.emplace_back(std::string() + "h1");
      param_names__.emplace_back(std::string() + "h0");
      param_names__.emplace_back(std::string() + "s0");
      param_names__.emplace_back(std::string() + "s1");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "sd_height");
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "height_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "mean_pred" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "h1_std");
    param_names__.emplace_back(std::string() + "s0_std");
    param_names__.emplace_back(std::string() + "ds_std");
    param_names__.emplace_back(std::string() + "ph0");
    param_names__.emplace_back(std::string() + "gamma_std");
    param_names__.emplace_back(std::string() + "sd_height_std");
    for (int sym1__ = 1; sym1__ <= n_elic; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "ds");
      param_names__.emplace_back(std::string() + "h1");
      param_names__.emplace_back(std::string() + "h0");
      param_names__.emplace_back(std::string() + "s0");
      param_names__.emplace_back(std::string() + "s1");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "sd_height");
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "height_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "mean_pred" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"h1_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s0_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ds_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ph0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sd_height_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_elic) + "},\"block\":\"parameters\"},{\"name\":\"ds\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"h1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"h0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"s0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"s1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sd_height\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"height_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_pred) + "},\"block\":\"generated_quantities\"},{\"name\":\"mean_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_pred) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"h1_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s0_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ds_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ph0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sd_height_std\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_elic) + "},\"block\":\"parameters\"},{\"name\":\"ds\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"h1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"h0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"s0\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"s1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sd_height\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"height_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_pred) + "},\"block\":\"generated_quantities\"},{\"name\":\"mean_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_pred) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + n_elic);
    const size_t num_transformed = emit_transformed_parameters * (((((((1 +
      1) + 1) + 1) + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((n_pred +
      n_pred));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + n_elic);
    const size_t num_transformed = emit_transformed_parameters * (((((((1 +
      1) + 1) + 1) + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((n_pred +
      n_pred));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_height_namespace::model_height;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_height_namespace::profiles__;
}
#endif
#endif
